### ISSUE TITLE
Price slider range can not work 

### ISSUE THREAD

**Issue by michaeldyl520** [NikZh/magento2-multiple-layered-navigation#14]
Price slider range can not work,can you fixed it? See gif below:
![20171030153355](https://user-images.githubusercontent.com/4518013/32159334-197bf6d6-bd88-11e7-9d10-58d7bd9a4f38.gif)

**Comment by NikZh** [comment]
Price slider is a beta feature, but it works http://m2-ln.nikzh.pp.ua/women/bottoms-women/pants-women.html
Do you have any javascript errors? 
Maybe you just need to clean cache and re-deploy static content?

**Comment by michaeldyl520** [comment]
When I use the latest code.I don`t find the error.Maybe you already fixed it.Thanks.
