### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by murtuza5253** [NikZh/magento2-multiple-layered-navigation#15]
PHP Parse error:  syntax error, unexpected '?' in /var/www/html/shantijewel/app/code/Niks/LayeredNavigation/Model/Url/Hydrator.php on line 127

**Comment by sagar-magento** [comment]
same issue occurs,

Parse error: syntax error, unexpected '?' in /var/www/html/magento2/app/code/Niks/LayeredNavigation/Model/Url/Hydrator.php on line 127

**Comment by murtuza5253** [comment]
@drcsystems78 I solve this error by replacing following code 

          $attributeParts[] = $options[$value] ? $options[$value] : false;

**Comment by NikZh** [comment]
please don't use php5 with magento 2 ;)
