### ISSUE TITLE
install all but not see multiselect 

### ISSUE THREAD

**Issue by alekseysavitsky** [NikZh/magento2-multiple-layered-navigation#2]
what can be wrong? do all like in instruction.

**Comment by NikZh** [comment]
If this extension was successfully installed, without any errors, try to clean all magento cache. Then check please magento extensions list in admin panel: 
http://screencast.com/t/xHDhY0CBNd2C
http://screencast.com/t/nsKnTYqSkAI

If Niks_LayeredNavigation appears in this list, you can use multiple select in layered navigation:
http://screencast.com/t/XmVk15eeGdU
