### ISSUE TITLE
Not working with catalogsearch

### ISSUE THREAD

**Issue by Taral-Patoliya** [NikZh/magento2-multiple-layered-navigation#3]
Hello,
I installed the module in my magento2 installation and its working for categorypage, but same is not the case with catalogsearch.

However, there is a commented out section in the di.xml 
https://github.com/NikZh/magento2-multiple-layered-navigation/blob/master/etc/di.xml#L13

I tried to make it possible to work on search result but it generates exceptions.

**Comment by mustdobetter** [comment]
H Taral-Patoliya,

I have just added a new pull request which adds support for catalog search: #5.

**Comment by NikZh** [comment]
added at 0.0.2 version
