### ISSUE TITLE
Price Multiselct 

### ISSUE THREAD

**Issue by vishaltajpara** [NikZh/magento2-multiple-layered-navigation#7]
Hello,

I have install this module, Custom attribute working multi select perfectly.
But Price and Category multi select not working.

**Comment by nilarocks** [comment]
Same here. price Filter not working with multiple select

**Comment by NikZh** [comment]
Just enable price slider in admin panel for price range

**Comment by nilarocks** [comment]
But i do not want to Price slider. I want to same as magento default for price Also Multiple category and Attribute  working fine. Here, Price filter generate wrong url. Look Below

With Extension:
For Single Price
Url: https://www.xyz.com/category.html?Price=-100       
For Multiple Price
Url: https://www.xyz.com/category.html?price=-100_40-50
->Give all data under -100 price.

Magento Defualt
For Single Price
Url: https://www.xyz.com/category.html?price=-100       
For Multiple Price
Url: https://www.xyz.com/category.html?price=40-50%2C-100
->Give only those data who under price 40-50

how can i remove price from code from extension?

**Comment by NikZh** [comment]
Fixed in 0.1.3
