### ISSUE TITLE
can't compile - magento class not found

### ISSUE THREAD

**Issue by robert-schmidt** [NikZh/magento2-multiple-layered-navigation#8]
Hi there.

When I try to compile the code, I get the following error: 
PHP Fatal error:  Class 'Magento\CatalogSearch\Model\Adapter\Aggregation\Checker\Query\CatalogView' not found in /var/www/public/app/code/Buzznative/LayeredNavigation/Model/Adapter/Aggregation/Checker/Query/CatalogView.php on line 12

Indeed, that class doesn't exist in that location.

I'm using 2.1.8. 

The class is not there in 2.1.7 either, just checked. 

Thanks.

**Comment by NikZh** [comment]
fixed at last version
