### ISSUE TITLE
Not work for Magento 2.2.0

### ISSUE THREAD

**Issue by gizmocn** [NikZh/magento2-multiple-layered-navigation#9]
I found it is not work for newest Magento 2.2.0, any suggest?

**Comment by gizmocn** [comment]
Thanks for prompt response, I just tested it and it is work for attribute, all attribute is showed with correct item number. 
It seem two plugins is missing, Niks\LayeredNavigation\Plugin\Preprocessor and Niks\LayeredNavigation\Plugin\CategoryAggregation.

**Comment by NikZh** [comment]
those plugins are there https://github.com/NikZh/magento2-multiple-layered-navigation/tree/master/Plugin, maybe you need to start di compilation

**Comment by gizmocn** [comment]
Got it, now the module is working for Magento 2.2.0 without problem, thanks.

I will close this issue.
